config/routes.rb
Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql" if Rails.env.development?
  post "/graphql", to: "graphql#execute"
  devise_for :admins, only: []

  resource :session,
           only: [],
           as: "admin_session",
           path: "/admins",
           controller: "admins/sessions" do
    get :new, path: "sign_in", as: "new"
    post :create, path: "sign_in"
    delete :destroy, path: "sign_out", as: "destroy"
  end

  resource :registration,
           only: %i[new create edit update destroy],
           as: "admin_registration",
           path: "/admins",
           controller: "admins/registrations",
           path_names: { new: "sign_up" }

  resource :invitation,
           only: %i[create update],
           as: "admin_invitation",
           path: "/admins/invitation" do
    get :edit, path: "accept", as: :accept
  end

  resource :password,
           only: %i[new create edit update],
           as: "admin_password",
           path: "/admins/password",
           controller: "admins/passwords"

  class SiteAdminConstraint
    def matches?(request)
      JWT.decode(request.session[:jwt_token], ENV["JWT_SECRET"], true, { algorithm: "HS512" }).first["site_admin"]
    rescue JWT::DecodeError
      false
    end
  end

  # TODO: the sidekiq ui should be part of the API part of Cuttlefish and not
  # part of the admin interface
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq", constraints: SiteAdminConstraint.new

  resources :admins, only: %i[index destroy]
  resources :emails, only: %i[index show], as: :deliveries,
                     controller: "deliveries" do
    member do
      get "html"
    end
  end
  # Allow "." in the id's by using the constraint
  resources :addresses, only: [], constraints: { id: %r{[^/]+} } do
    member do
      get :from
      get :to
    end
  end
  resources :test_emails, only: %i[new create]
  resources :apps do
    resources :emails, only: :index, as: :deliveries, controller: "deliveries"
    resources :clients, only: :index, as: :clients, controller: "clients"
    resources :deny_lists, only: %i[index destroy], as: :deny_lists, controller: "deny_lists"

    member do
      get "dkim"
      get "webhook"
      post "toggle_dkim"
      post "upgrade_dkim"
    end
  end

  resources :deny_lists, only: %i[index destroy]
  resources :teams, only: :index do
    collection do
      post "invite"
    end
  end

  resources :clients, only: :index
  resources :domains, only: :index

  get ".well-known/acme-challenge/:token", to: "acme_challenges#show"

  root to: "landing#index"

  get "dash" => "main#index"
  get "status_counts" => "main#status_counts"
  get "reputation" => "main#reputation"

  # Open tracking gifs
  get "o2/:delivery_id/:hash" => "tracking#open", as: "tracking_open"

  # Link tracking
  get "l2/:delivery_link_id/:hash" => "tracking#click", as: "tracking_click"

  get "/documentation" => "documentation#index"
end

app/controllers/test_emails_controller.rb
# frozen_string_literal: true

class TestEmailsController < ApplicationController
  # We're using the simple_format helper below. Ugly but quick by bringing it
  # into the controller
  include ActionView::Helpers::TextHelper

  def new
    result = api_query
    @data = result.data
    @to = helpers.email_with_name(@data.viewer)
    @subject = "This is a test email from Cuttlefish"
    @text = <<~TEXT
      Hello folks. Hopefully this should have worked and you should
      be reading this. So, all is good.

      Love,
      The Awesome Cuttlefish
      <a href="http://cuttlefish.io">http://cuttlefish.io</a>
    TEXT
  end

  # Send a test email
  def create
    # TODO: Check for errors
    api_query app_id: params[:app_id],
              from: params[:from],
              to: params[:to],
              cc: params[:cc],
              subject: params[:subject],
              textPart: params[:text],
              htmlPart: simple_format(params[:text])

    flash[:notice] = "Test email sent"
    redirect_to deliveries_url
  end
end

app/views/test_emails/new.html.haml
.page-header
  %h1 Send test email

= form_tag test_emails_path, class: "form-horizontal" do
  %fieldset
    - if @data.apps.empty?
      %p
        Before you can send email via Cuttlefish you will need to #{link_to "create an App", new_app_path}. Each App has its
        own settings and usually relates to one application from which you're sending the emails.
    - else
      .control-group
        %label.control-label(for="app_id") App
        .controls
          = select_tag :app_id, options_from_collection_for_select(@data.apps, "id", "name")
      .control-group
        %label.control-label(for="inputFrom") From
        .controls
          = text_field_tag :from, @from, class: "span6", id: "inputFrom", placeholder: "From"
      .control-group
        %label.control-label(for="inputTo") To
        .controls
          = text_field_tag :to, @to, class: "span6", id: "inputTo", placeholder: "To"
      .control-group
        %label.control-label(for="inputCc") Cc
        .controls
          = text_field_tag :cc, @cc, class: "span6", id: "inputCc", placeholder: "Cc"
      .control-group
        %label.control-label(for="inputSubject") Subject
        .controls
          = text_field_tag :subject, @subject, class: "span6", id: "inputSubject", placeholder: "Subject"
      .control-group
        %label.control-label(for="inputText") Your message
        .controls
          = text_area_tag :text, @text, class: "span6", id: "inputText", placeholder: "Your message", rows: 8 do
            = @text
      .control-group
        .controls
          = button_tag "Send test email", class: "btn"