config/routes.rb
Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql" if Rails.env.development?
  post "/graphql", to: "graphql#execute"
  devise_for :admins, only: []

  resource :session,
           only: [],
           as: "admin_session",
           path: "/admins",
           controller: "admins/sessions" do
    get :new, path: "sign_in", as: "new"
    post :create, path: "sign_in"
    delete :destroy, path: "sign_out", as: "destroy"
  end

  resource :registration,
           only: %i[new create edit update destroy],
           as: "admin_registration",
           path: "/admins",
           controller: "admins/registrations",
           path_names: { new: "sign_up" }

  resource :invitation,
           only: %i[create update],
           as: "admin_invitation",
           path: "/admins/invitation" do
    get :edit, path: "accept", as: :accept
  end

  resource :password,
           only: %i[new create edit update],
           as: "admin_password",
           path: "/admins/password",
           controller: "admins/passwords"

  class SiteAdminConstraint
    def matches?(request)
      JWT.decode(request.session[:jwt_token], ENV["JWT_SECRET"], true, { algorithm: "HS512" }).first["site_admin"]
    rescue JWT::DecodeError
      false
    end
  end

  # TODO: the sidekiq ui should be part of the API part of Cuttlefish and not
  # part of the admin interface
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq", constraints: SiteAdminConstraint.new

  resources :admins, only: %i[index destroy]
  resources :emails, only: %i[index show], as: :deliveries,
                     controller: "deliveries" do
    member do
      get "html"
    end
  end
  # Allow "." in the id's by using the constraint
  resources :addresses, only: [], constraints: { id: %r{[^/]+} } do
    member do
      get :from
      get :to
    end
  end
  resources :test_emails, only: %i[new create]
  resources :apps do
    resources :emails, only: :index, as: :deliveries, controller: "deliveries"
    resources :clients, only: :index, as: :clients, controller: "clients"
    resources :deny_lists, only: %i[index destroy], as: :deny_lists, controller: "deny_lists"

    member do
      get "dkim"
      get "webhook"
      post "toggle_dkim"
      post "upgrade_dkim"
    end
  end

  resources :deny_lists, only: %i[index destroy]
  resources :teams, only: :index do
    collection do
      post "invite"
    end
  end

  resources :clients, only: :index
  resources :domains, only: :index

  get ".well-known/acme-challenge/:token", to: "acme_challenges#show"

  root to: "landing#index"

  get "dash" => "main#index"
  get "status_counts" => "main#status_counts"
  get "reputation" => "main#reputation"

  # Open tracking gifs
  get "o2/:delivery_id/:hash" => "tracking#open", as: "tracking_open"

  # Link tracking
  get "l2/:delivery_link_id/:hash" => "tracking#click", as: "tracking_click"

  get "/documentation" => "documentation#index"
end

app/views/apps/_setting_up_your_dns.html.haml
.alert.alert-info
  - if dkim_dns.lookup_value.nil?
    You will need to add a TXT record to your DNS.
  - else
    Your DNS doesn't look to be set up correctly

%h2 Setting up your DNS

- if provider.nil?
  %p
    These are generic instructions for updating your DNS. For instructions for your specific
    DNS provider choose below.
- elsif provider == "dns_made_easy"
  %p
    These are specific instructions for updating your DNS on #{link_to "DNS Made Easy", "http://www.dnsmadeeasy.com/"}. If you use a different provider choose below.
- elsif provider == "cloudflare"
  %p
    These are specific instructions for updating your DNS on #{link_to "CloudFlare", "https://www.cloudflare.com/"}. If you use a different provider choose below.

.btn-group
  %button.btn.btn-default.dropdown-toggle{type: "button", "data-toggle" => "dropdown", "aria-expanded" => false}
    - if provider == "dns_made_easy"
      DNS Made Easy
    - elsif provider == "cloudflare"
      CloudFlare
    - else
      Generic DNS provider
    %span.caret
  %ul.dropdown-menu(role="menu")
    %li= link_to "Generic DNS provider", provider: nil
    %li= link_to "DNS Made Easy", provider: "dns_made_easy"
    %li= link_to "CloudFlare", provider: "cloudflare"
%p
  Your DNS provider not listed? Please
  = link_to "file an issue on GitHub", "https://github.com/mlandauer/cuttlefish/issues/new"
  with what the instructions should say.

%table.table.dns
  %thead
    %tr
      %th Name
      %th Value
  %tbody
    %tr
      %td= dkim_dns.name
      %td
        %pre
          - if provider.nil? || provider == "cloudflare"
            = dkim_dns.target_value
          - elsif provider == "dns_made_easy"
            = quote_long_dns_txt_record(dkim_dns.target_value)
          - else
            raise

%p
  %strong Reload
  this page after you have configured your DNS

app/views/apps/dkim.html.haml
.page-header
  %h1 Transparently send mail from your own domain
  %p
    In
    = link_to "Google Mail", "https://gmail.com"
    get rid of "via #{Rails.configuration.cuttlefish_domain}" when viewing
    email sent from your own domain by giving Cuttlefish permission to send email on your behalf.

- if @app.from_domain.present?
  - if @app.dkim_dns_record.configured?
    %p Your DNS looks to be correctly configured.
    - if @app.dkim_dns_record.upgrade_required?
      = button_to "Switch to using new DNS record", upgrade_dkim_app_path(@app.id), class: "btn btn-primary"
    - else
      = button_to (@app.dkim_enabled ? "Disable DKIM" : "Enable DKIM"), toggle_dkim_app_path(@app.id), class: "btn btn-primary"
  - else
    = render 'setting_up_your_dns', provider: @provider, dkim_dns: @app.dkim_dns_record

%h2 Domain

= semantic_form_for @app, as: :app, url: app_path(@app.id), method: :put, html: {class: "form-horizontal"} do |f|
  = f.semantic_errors
  = f.input :from_domain, label: "Email from domain", placeholder: "angelfishsocute.com", hint: "Domain that all emails in this app will be sent from"
  = f.actions do
    = f.action :submit, label: "Update domain"

app/views/apps/edit.html.haml
.page-header
  %h1 Edit App

= semantic_form_for @app, as: :app, url: app_path(@app.id), method: :put, html: {class: "form-horizontal"} do |f|
  = f.semantic_errors
  = f.inputs "Basic" do
    = f.input :name, placeholder: "Angelfish", input_html: {class: "span6"}, label: 'Name', hint: ''
  = f.inputs "Tracking" do
    = f.input :click_tracking_enabled, as: :boolean, hint: "Rewrite all the links in html emails so that you can find out when users click them", label: "Click tracking enabled", placeholder: ""
    = f.input :open_tracking_enabled, as: :boolean, hint: "Adds a small transparent image to the end of html emails so that you can find out when an email is opened", label: "Open tracking enabled", placeholder: ''
    = f.input :custom_tracking_domain, label: 'Custom tracking domain', placeholder: "email.angelfishsocute.com", hint: "Leave blank if you want to use default domain (#{Rails.configuration.cuttlefish_domain}) for open and link tracking. You can set this later too."
  = f.actions do
    = f.action :submit, label: "Update App"

.alert.alert-block
  %h2 Remove this App
  %p
    Here lies danger. Removing the app from Cuttlefish will permanently delete the app, the associated emails and can not be undone!
  %p
    = button_to "Remove App", app_path(@app.id), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger"

app/views/apps/index.html.haml
.page-header
  %h1 Apps

%p
  All emails are sent through apps, which represent the application that sends the email.
  Each App has its own settings and its own smtp authentication settings to contact the
  Cuttlefish SMTP server.

%p
  = link_to "New App", new_app_path, class: "btn btn-primary"

%table.table
  %thead
    %tr
      %th
        Name
  %tbody(data-provides="rowlink")
    - @apps.each do |app|
      - if app.dkim_enabled && app.dkim_dns_record.upgrade_required
        %tr.info
          %td
            %i.fa.fa-exclamation-circle
            = link_to app.name, app_path(app.id)
      - else
        %tr
          %td
            = link_to app.name, app_path(app.id)

app/views/apps/new.html.haml
.page-header
  %h1 New App

= semantic_form_for @app, as: :app, url: apps_path, html: {class: "form-horizontal"} do |f|
  = f.semantic_errors
  = f.inputs "Basic" do
    = f.input :name, placeholder: "Angelfish", input_html: {class: "span6"}
  = f.inputs "Tracking" do
    = f.input :click_tracking_enabled, as: :boolean, hint: "Rewrite all the links in html emails so that you can find out when users click them"
    = f.input :open_tracking_enabled, as: :boolean, hint: "Adds a small transparent image to the end of html emails so that you can find out when an email is opened"
    = f.input :custom_tracking_domain, placeholder: "email.angelfishsocute.com", hint: "Leave blank if you want to use default domain (#{Rails.configuration.cuttlefish_domain}) for open and link tracking. You can set this later too."
  = f.actions do
    = f.action :submit, label: "Create App"

app/views/apps/show.html.haml
.page-header
  %h1= @app.name

- if @app.dkim_enabled && @app.permissions.dkim? && @app.dkim_dns_record.upgrade_required
  .alert.alert-info
    %p
      %i.fa.fa-exclamation-circle
      Please upgrade your DNS record for DKIM.
    %p
      To support multiple apps using
      the same domain, we're updating the format of the DNS record for DKIM.
      In the meantime things will continue to work with the old DNS record.
    %p= link_to "Upgrade DNS settings", dkim_app_path(@app.id), class: "btn"


%ul
  %li= link_to "Emails sent via this app", app_deliveries_path(@app.id)
  - unless @app.cuttlefish?
    %li= link_to "How to send mail via Cuttlefish for #{@app.name}", documentation_path(anchor: "app-#{@app.id}")

- if @app.permissions.update?
  %p= link_to "Edit Settings", edit_app_path(@app.id), class: "btn"

- if @app.dkim_enabled && @app.permissions.dkim?
  %hr
  %h3 Improve delivery
  %p
    DomainKeys Identified Mail (DKIM) improves the delivery of your emails by automatically cryptographically
    signing each email so that the recipient can check that it was indeed sent by you.
  = button_to "Disable DKIM", toggle_dkim_app_path(@app.id), class: "btn btn-primary"
- elsif !@app.dkim_enabled && @app.permissions.dkim?
  %h3 What to do next
  %p= link_to "Transparently send mail from your own domain", dkim_app_path(@app.id)

%h3 Event Webhook
%p
  Integrate your web application more closely with Cuttlefish by getting Cuttlefish
  to send a callback to a endpoint of your choosing whenever an email for this
  app is delivered.

%p= link_to "Setting and documentation for webhook", webhook_app_path(@app.id)

- if @app.custom_tracking_domain.present? && !@app.custom_tracking_domain_ssl_enabled
  .alert.alert-info
    %h3 Custom domain open and click tracking is temporarily using "http"
    %p
      An SSL certificate is being generated for your custom tracking domain right now.
      It may take a few minutes for this to come through. In the meantime the open
      and click tracking urls will start with "http".

app/views/apps/webhook.html.haml
.page-header
  %h1 Event Webhook
  %p
    Integrate your web application more closely with Cuttlefish by getting Cuttlefish
    to send a callback to a endpoint of your choosing whenever an email for this
    app is delivered.

%h2 Delivery Event
%p
  When an email for this app gets delivered or fails to get delivered a POST
  is sent to the webhook URL with the following JSON body

:coderay
  #!json
  {
    "key": "#{@data.app.webhook_key}",
    "delivery_event": {
      "time": "2020-08-27T02:10:17.000Z",
      "dsn": "2.0.0",
      "status": "delivered",
      "extended_status": "sent (250 Message accepted)",
      "email": {
        "id": 123,
        "message_id": "ABC@DEF.foo.com",
        "from": "matthew@oaf.org.au",
        "to": "joy@smart-unlimited.com",
        "subject": "This is a test email from Cuttlefish",
        "created_at": "2020-08-27T02:10:17.579Z",
        "meta_values": {}
      }
    }
  }

%h2 Secret Key
%p
  A secret key (just for this webhook and app) is sent along with the test event.
  This secret key should always be checked by the receiving end. This ensures
  that a malicious third party can not easily pretend to be a webhook from Cuttlefish
  and inject bad data into your system.

%p
  Secret key:
  %code= @data.app.webhook_key

%h2 Test Event
%p
  Once a webhook URL is entered, a test event is immediately sent as a POST
  with the following JSON body.

:coderay
  #!json
  {
    "key": "#{@data.app.webhook_key}",
    "test_event": {}
  }

%p This is used to validate the webhook URL

%h2 Setting

= semantic_form_for @app, as: :app, url: app_path(@app.id), method: :put, html: {class: "form-horizontal"} do |f|
  = f.semantic_errors
  = f.input :webhook_url, label: "Webhook URL", hint: "Leave empty if you don't need this", placeholder: "https://yourapp.com/events", input_html: {class: "span6"}
  = f.actions do
    = f.action :submit, label: "Update webhook"