config/routes.rb
Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql" if Rails.env.development?
  post "/graphql", to: "graphql#execute"
  devise_for :admins, only: []

  resource :session,
           only: [],
           as: "admin_session",
           path: "/admins",
           controller: "admins/sessions" do
    get :new, path: "sign_in", as: "new"
    post :create, path: "sign_in"
    delete :destroy, path: "sign_out", as: "destroy"
  end

  resource :registration,
           only: %i[new create edit update destroy],
           as: "admin_registration",
           path: "/admins",
           controller: "admins/registrations",
           path_names: { new: "sign_up" }

  resource :invitation,
           only: %i[create update],
           as: "admin_invitation",
           path: "/admins/invitation" do
    get :edit, path: "accept", as: :accept
  end

  resource :password,
           only: %i[new create edit update],
           as: "admin_password",
           path: "/admins/password",
           controller: "admins/passwords"

  class SiteAdminConstraint
    def matches?(request)
      JWT.decode(request.session[:jwt_token], ENV["JWT_SECRET"], true, { algorithm: "HS512" }).first["site_admin"]
    rescue JWT::DecodeError
      false
    end
  end

  # TODO: the sidekiq ui should be part of the API part of Cuttlefish and not
  # part of the admin interface
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq", constraints: SiteAdminConstraint.new

  resources :admins, only: %i[index destroy]
  resources :emails, only: %i[index show], as: :deliveries,
                     controller: "deliveries" do
    member do
      get "html"
    end
  end
  # Allow "." in the id's by using the constraint
  resources :addresses, only: [], constraints: { id: %r{[^/]+} } do
    member do
      get :from
      get :to
    end
  end
  resources :test_emails, only: %i[new create]
  resources :apps do
    resources :emails, only: :index, as: :deliveries, controller: "deliveries"
    resources :clients, only: :index, as: :clients, controller: "clients"
    resources :deny_lists, only: %i[index destroy], as: :deny_lists, controller: "deny_lists"

    member do
      get "dkim"
      get "webhook"
      post "toggle_dkim"
      post "upgrade_dkim"
    end
  end

  resources :deny_lists, only: %i[index destroy]
  resources :teams, only: :index do
    collection do
      post "invite"
    end
  end

  resources :clients, only: :index
  resources :domains, only: :index

  get ".well-known/acme-challenge/:token", to: "acme_challenges#show"

  root to: "landing#index"

  get "dash" => "main#index"
  get "status_counts" => "main#status_counts"
  get "reputation" => "main#reputation"

  # Open tracking gifs
  get "o2/:delivery_id/:hash" => "tracking#open", as: "tracking_open"

  # Link tracking
  get "l2/:delivery_link_id/:hash" => "tracking#click", as: "tracking_click"

  get "/documentation" => "documentation#index"
end

app/models/deny_list.rb
# frozen_string_literal: true

class DenyList < ApplicationRecord
  belongs_to :app
  belongs_to :address
  belongs_to :caused_by_postfix_log_line, class_name: "PostfixLogLine"
end

app/controllers/deny_lists_controller.rb
# frozen_string_literal: true

class DenyListsController < ApplicationController
  def index
    @deny_lists = WillPaginate::Collection.create(
      params[:page] || 1,
      WillPaginate.per_page
    ) do |pager|
      @dsn = params[:dsn]
      result = api_query limit: pager.per_page,
                         offset: pager.offset,
                         app_id: params[:app_id],
                         dsn: @dsn
      pager.replace(result.data.blocked_addresses.nodes)
      pager.total_entries = result.data.blocked_addresses.total_count
      @data = result.data
      @apps = @data.apps
      @app = @apps.find { |a| a.id == params[:app_id] } if params[:app_id]
    end
  end

  def destroy
    result = api_query id: params[:id]
    blocked_address = result.data.remove_blocked_address.blocked_address
    if blocked_address
      flash[:notice] = "#{blocked_address.address} removed from deny list"
    else
      flash[:alert] = "Couldn't remove from deny list. " \
                      "You probably don't have the necessary permissions."
    end
    redirect_back(fallback_location: deny_lists_url)
  end
end

app/helpers/deny_lists_helper.rb
# frozen_string_literal: true

module DenyListsHelper
  def canonical_deny_lists_path(app:, dsn:)
    if app
      app_deny_lists_path(app.id, dsn: dsn)
    else
      deny_lists_path(dsn: dsn)
    end
  end
end

app/views/deny_lists/index.html.haml
.page-header
  %h1 Deny listed email addresses
  %p
    This list is auto-populated with any email addresses that bounce. Any further emails to addresses
    in this list will be "held back" and not sent.
  %p
    After one week addresses are automatically removed from this list

.btn-group
  %button.btn.dropdown-toggle(data-toggle="dropdown")
    - if @app.nil?
      All Apps
    - else
      = @app.name
    %span.caret
  %ul.dropdown-menu
    %li= link_to "All Apps", canonical_deny_lists_path(app: nil, dsn: @dsn)
    - @apps.each do |app|
      %li= link_to app.name, canonical_deny_lists_path(app: app, dsn: @dsn)

.btn-group
  %button.btn.dropdown-toggle(data-toggle="dropdown")
    - if @dsn.nil?
      All DSNs
    - else
      = @dsn
      &mdash;
      = DSN.hard_bounce_codes_short_descriptions[@dsn]

    %span.caret
  %ul.dropdown-menu
    %li= link_to "All DSNs", canonical_deny_lists_path(app: @app, dsn: nil)
    - DSN.hard_bounce_codes_short_descriptions.each do |dsn, description|
      %li
        = link_to canonical_deny_lists_path(app: @app, dsn: dsn) do
          = dsn
          &mdash;
          = description

= paginated_section @deny_lists, renderer: PagerRenderer, previous_label: image_tag("pager/previous.png", size: "13x14"), next_label: image_tag("pager/next.png", size: "13x14"), text: "Address" do
  %p.count= page_entries_info @deny_lists, model: "deny listed email addresses"
  - if @deny_lists.size > 0
    %table.table.table-striped
      %thead
        %tr
          %th Email address
          %th App
          %th{colspan: 2} Reason deny listed
          %th When
      %tbody
        - @deny_lists.each do |deny_list|
          %tr
            %td= deny_list.address
            %td= deny_list.app.name
            %td= deny_list.because_of_delivery_event.dsn
            %td= link_to truncate(deny_list.because_of_delivery_event.extended_status, length: 160), delivery_path(deny_list.because_of_delivery_event.email.id)
            %td
              = time_ago_in_words(deny_list.because_of_delivery_event.time)
              ago
            %td
              = button_to "Remove", deny_list_path(deny_list.id), method: :delete, class: "btn btn-danger"